-- Seed cybersecurity assessment bank questions (idempotent).
-- Fixes: required "id"/timestamps on AssessmentBankQuestion; removes SubCategoryConfiguration inserts
-- (that table is created in 20260410180000 — seeded in 20260417150000_seed_cybersecurity_subcategories).

INSERT INTO "AssessmentBankQuestion" (
    "id",
    "questionId",
    "riskAreaId",
    "sortOrderGlobal",
    "isVisible",
    "text",
    "helpText",
    "learnMore",
    "riskRelevance",
    "type",
    "options",
    "required",
    "weight",
    "scoreMap",
    "branchingDependsOn",
    "branchingPredicate",
    "profileConditionKey",
    "omitMaturityScoreWhenYes",
    "createdAt",
    "updatedAt"
) VALUES
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_password_device_management',
    'cybersecurity',
    1,
    true,
    'Who manages passwords, devices, and updates?',
    'This reveals whether cybersecurity responsibility is clearly owned or informally assumed.',
    NULL,
    'When no one is accountable, updates get skipped, passwords get reused, and small gaps compound into major exposure.',
    'single-choice',
    '[
        {"value": "no_ownership", "label": "No ownership", "description": "No one specifically responsible"},
        {"value": "informal", "label": "Informal", "description": "Ad hoc responsibility"},
        {"value": "assigned", "label": "Assigned", "description": "Specific person responsible"},
        {"value": "centralized_audited", "label": "Centralized and audited", "description": "Formal ownership with oversight"}
    ]'::json,
    true,
    3,
    '{"no_ownership": 0, "informal": 1, "assigned": 2, "centralized_audited": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_family_online_rules',
    'cybersecurity',
    2,
    true,
    'Does your family have agreed on basic do''s and don''ts for online activity?',
    'Shared norms reduce accidental risk (e.g., clicking unknown links, oversharing on social media).',
    NULL,
    'Without alignment, the least cautious household member becomes the entry point for attackers.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No established rules"},
        {"value": "verbal", "label": "Verbal", "description": "Informal verbal agreements"},
        {"value": "documented", "label": "Documented", "description": "Written guidelines"},
        {"value": "documented_reinforced", "label": "Documented and reinforced", "description": "Written and actively enforced"}
    ]'::json,
    true,
    2,
    '{"none": 0, "verbal": 1, "documented": 2, "documented_reinforced": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_family_education',
    'cybersecurity',
    3,
    true,
    'Have family members received any guidance or education on how to stay safe online?',
    'Education is one of the strongest risk reducers. Most cyber incidents exploit human behavior, not technology.',
    NULL,
    'Training dramatically lowers susceptibility to phishing and scams.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No training provided"},
        {"value": "one_time", "label": "One-time", "description": "Single training session"},
        {"value": "periodic", "label": "Periodic", "description": "Regular but infrequent"},
        {"value": "ongoing_role_based", "label": "Ongoing and role-based", "description": "Continuous and tailored"}
    ]'::json,
    true,
    3,
    '{"none": 0, "one_time": 1, "periodic": 2, "ongoing_role_based": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_risk_awareness',
    'cybersecurity',
    4,
    true,
    'How familiar are family members with basic cyber risks (phishing, scams)?',
    'This gauges vulnerability to social engineering.',
    NULL,
    'Low awareness increases the likelihood of financial loss, identity theft, or account takeover.',
    'single-choice',
    '[
        {"value": "low", "label": "Low", "description": "Minimal understanding"},
        {"value": "basic", "label": "Basic", "description": "Some awareness"},
        {"value": "moderate", "label": "Moderate", "description": "Good understanding"},
        {"value": "high_tested", "label": "High and tested", "description": "Advanced awareness with validation"}
    ]'::json,
    true,
    2,
    '{"low": 0, "basic": 1, "moderate": 2, "high_tested": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_insurance',
    'cybersecurity',
    5,
    true,
    'Do you have personal or family cybersecurity insurance?',
    'Insurance can offset financial losses, cover forensic services, and provide crisis response.',
    NULL,
    'Its absence means incidents may result in unplanned emergency spending and reputational damage.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No coverage"},
        {"value": "exploring", "label": "Exploring", "description": "Considering options"},
        {"value": "active_policy", "label": "Active policy", "description": "Current coverage"},
        {"value": "active_aligned", "label": "Active and aligned to risk", "description": "Comprehensive and appropriate"}
    ]'::json,
    true,
    2,
    '{"none": 0, "exploring": 1, "active_policy": 2, "active_aligned": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_travel_practices',
    'cybersecurity',
    6,
    true,
    'What additional cybersecurity practices do family members utilize while traveling domestically or internationally?',
    'Travel increases exposure to insecure Wi-Fi, border searches, and device theft.',
    NULL,
    'This question identifies gaps during the household''s highest-risk periods.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No special precautions"},
        {"value": "minimal", "label": "Minimal", "description": "Basic awareness"},
        {"value": "defined", "label": "Defined", "description": "Clear practices"},
        {"value": "strict_protocols", "label": "Strict protocols", "description": "Comprehensive security measures"}
    ]'::json,
    true,
    2,
    '{"none": 0, "minimal": 1, "defined": 2, "strict_protocols": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_device_inventory',
    'cybersecurity',
    10,
    true,
    'Can you provide an inventory of all devices: computers, phones, tablets, smart TVs, IoT devices, routers?',
    'You can''t protect what you don''t know exists.',
    NULL,
    'Unknown or forgotten devices are common attack vectors.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No inventory"},
        {"value": "partial", "label": "Partial", "description": "Some devices documented"},
        {"value": "complete", "label": "Complete", "description": "All devices known"},
        {"value": "dynamic_maintained", "label": "Dynamic and maintained", "description": "Current and updated inventory"}
    ]'::json,
    true,
    3,
    '{"none": 0, "partial": 1, "complete": 2, "dynamic_maintained": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_software_updates',
    'cybersecurity',
    11,
    true,
    'Are all devices running current software updates?',
    'Updates patch known vulnerabilities.',
    NULL,
    'Unpatched devices are one of the easiest targets for attackers.',
    'single-choice',
    '[
        {"value": "outdated", "label": "Outdated", "description": "Behind on updates"},
        {"value": "manual", "label": "Manual", "description": "Updated when remembered"},
        {"value": "current", "label": "Current", "description": "Up to date"},
        {"value": "automated_enforced", "label": "Automated and enforced", "description": "Automatic updates enabled"}
    ]'::json,
    true,
    3,
    '{"outdated": 0, "manual": 1, "current": 2, "automated_enforced": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_auto_updates',
    'cybersecurity',
    12,
    true,
    'Are all devices set to auto update?',
    'Manual updating fails over time.',
    NULL,
    'Auto-updates reduce reliance on memory and discipline.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "All manual"},
        {"value": "some_devices", "label": "Some devices", "description": "Partial automation"},
        {"value": "most_devices", "label": "Most devices", "description": "Majority automated"},
        {"value": "all_devices", "label": "All devices", "description": "Fully automated"}
    ]'::json,
    true,
    2,
    '{"none": 0, "some_devices": 1, "most_devices": 2, "all_devices": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_network_segmentation',
    'cybersecurity',
    13,
    true,
    'Are separate networks used for guests, home automation, IoT, and critical devices?',
    'Network segmentation limits damage if one device or guest network is compromised.',
    NULL,
    'Configure separate networks for work, family, and guests.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "Single network"},
        {"value": "limited", "label": "Limited", "description": "Some separation"},
        {"value": "segmented", "label": "Segmented", "description": "Multiple networks"},
        {"value": "fully_segmented", "label": "Fully segmented", "description": "Complete isolation"}
    ]'::json,
    true,
    3,
    '{"none": 0, "limited": 1, "segmented": 2, "fully_segmented": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_wifi_security',
    'cybersecurity',
    14,
    true,
    'Are Wi-Fi networks secured with strong encryption and password?',
    'Weak Wi-Fi security allows attackers to intercept data or access connected devices directly.',
    NULL,
    'Home Wi-Fi admin access restricted and credentials unique.',
    'single-choice',
    '[
        {"value": "weak_default", "label": "Weak/default", "description": "Default or weak security"},
        {"value": "moderate", "label": "Moderate", "description": "Basic encryption"},
        {"value": "strong_encryption", "label": "Strong encryption", "description": "WPA3 or equivalent"},
        {"value": "enterprise_grade", "label": "Enterprise-grade and hidden SSID", "description": "Advanced security"}
    ]'::json,
    true,
    2,
    '{"weak_default": 0, "moderate": 1, "strong_encryption": 2, "enterprise_grade": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_password_manager',
    'cybersecurity',
    20,
    true,
    'Are password managers used, and are they secure?',
    'Password managers reduce reuse and weak passwords—two of the biggest causes of account compromise.',
    NULL,
    'Password manager is deployed and used by all family members.',
    'single-choice',
    '[
        {"value": "reused_simple", "label": "Reused/simple", "description": "Weak password practices"},
        {"value": "some_complexity", "label": "Some complexity", "description": "Mixed practices"},
        {"value": "password_manager", "label": "Password Manager", "description": "Using password manager"},
        {"value": "enterprise_grade", "label": "Enterprise-grade and enforced", "description": "Advanced password management"}
    ]'::json,
    true,
    3,
    '{"reused_simple": 0, "some_complexity": 1, "password_manager": 2, "enterprise_grade": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    replace(gen_random_uuid()::text, '-', ''),
    'cyber_mfa_enabled',
    'cybersecurity',
    21,
    true,
    'Is MFA enabled on sensitive accounts?',
    'Multi-factor authentication dramatically lowers the chance of unauthorized access, even if passwords are stolen.',
    NULL,
    'Multi-factor authentication enabled for banking, investments, email.',
    'single-choice',
    '[
        {"value": "none", "label": "None", "description": "No MFA"},
        {"value": "limited", "label": "Limited", "description": "Few accounts"},
        {"value": "critical_enabled", "label": "Enabled on critical", "description": "Important accounts"},
        {"value": "universal_phishing_resistant", "label": "Universal and phishing-resistant MFA", "description": "Comprehensive MFA"}
    ]'::json,
    true,
    3,
    '{"none": 0, "limited": 1, "critical_enabled": 2, "universal_phishing_resistant": 3}'::json,
    NULL,
    NULL,
    NULL,
    false,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT ("questionId") DO UPDATE SET
    "riskAreaId" = EXCLUDED."riskAreaId",
    "sortOrderGlobal" = EXCLUDED."sortOrderGlobal",
    "isVisible" = EXCLUDED."isVisible",
    "text" = EXCLUDED."text",
    "helpText" = EXCLUDED."helpText",
    "learnMore" = EXCLUDED."learnMore",
    "riskRelevance" = EXCLUDED."riskRelevance",
    "type" = EXCLUDED."type",
    "options" = EXCLUDED."options",
    "required" = EXCLUDED."required",
    "weight" = EXCLUDED."weight",
    "scoreMap" = EXCLUDED."scoreMap",
    "branchingDependsOn" = EXCLUDED."branchingDependsOn",
    "branchingPredicate" = EXCLUDED."branchingPredicate",
    "profileConditionKey" = EXCLUDED."profileConditionKey",
    "omitMaturityScoreWhenYes" = EXCLUDED."omitMaturityScoreWhenYes",
    "updatedAt" = EXCLUDED."updatedAt";
